CREATE TABLE HEADER
(
	TIMESTAMP CHAR(24) PRIMARY KEY,
	METHOD CHAR(10),
	MODEL CHAR(10),
	PARAM0 REAL,
	PARAM1 REAL,
	PARAM2 REAL,
	PARAM3 REAL,
	PARAM4 REAL,
	POPULATION_SIZE INT,
	ITERATIONS INT,
	RANDOM_SEED INT,
	RUN_TIME REAL,
	BEST_POINT TEXT,
	EVAL REAL
);
CREATE TABLE DETAILS
(
	TIMESTAMP CHAR(24),
	ITERATION INT,
	POPULATION_BEST REAL,
	POPULATION_WORST REAL,
	BEST REAL
);
